### ISSUE TITLE
Footnotes not working

### ISSUE THREAD

**Issue by Jade-mist** [dr-nyt/WuxiaWorld-Novel-Downloader#2]
Greetings,

I am reading book 3 of "I Shall Seal The Heavens" and I am noticing the footnotes are not appearing. Sometimes the number does not appear and sometimes there is a random number (e.g. "1"), but it does not link to anything at the end of the chapter and even if I go manually to the end, there is noting there (no footnotes). A good example is the beginning of Chapter 211 of "I Shall Seal The Heavens". You will notice the explanation of Bai Yunlai's name is missing.Another good example is Chapter 1 of "A Will Eternal". There are footnotes at the end of the chapter, but the numbers do not appear in the chapter itself.

I am really enjoying your product and I think it's the best out there in this field, but the lack of footnotes is really bothering me. Please try your best to fix it when you have the time.

Best wishes,
Jade-mist

**Comment by dr-nyt** [comment]
Hey Jad-mist,

I'm really glad you like my work. I will try to check up on the problem as soon as possible. 

Also just to make sure, when had you last downloaded the app? I'm asking because I've made some major changes to how the novels are compiled and added support for cover pages to be added automatically as well. You can read the [README](https://github.com/dr-nyt/WuxiaWorld-Novel-Downloader#usage) section for more details. 

If you already have the latest version then no worries, I'll get back to you as soon as I can :)

**Comment by Jade-mist** [comment]
Greetings,

I used Version 0.4, which I downloaded a week or so ago.

Best wishes,
Jade-mist

**Comment by dr-nyt** [comment]
Alright, I managed to fix the issue where the chapter numbers for the file names would be inconsistent. I'll try to fix up the other issue when I get free later today.

**Comment by dr-nyt** [comment]
DONE!
I managed to track down the bug and it was related to the HTML parser.

Anyway, I've tested your chapter 211 and it seems to be working now. I've also fixed a few minor bugs as well. I've also realized that because of this issue you found, chapter 211 was missing as much as half its content. I hope this didn't cause any inconvenience.

Feel free to let me know if you find any more issues. I'll mark this thread closed for now :)
